### ISSUE TITLE
Create a dugnad-bot for Mattermost

### ISSUE THREAD

**Issue by SindreKjelsrud** [fribyte-code/friBot#1]
## Dugnad

- [x] Send out message in dugnad-channel every monday and wednesday 📆 
- [x] Message should include that members need to react with ✅ if they're coming and ❌ if not
- [x] Could make it a bit more "interesting" with use of different emojis and such 💯 🧇 🧃

**Comment by polsevev** [comment]
Tror ikke jeg skal gjøre dette, tenkte det er et godt start-prosjekt for nye medlemmer :)

**Comment by SindreKjelsrud** [comment]
Merget inn sosial-funksjoner for denne boten! Tenkte den kan fungere som mer enn bare dugnadsbot 😅

**Comment by Cengelsen** [comment]
Jeg foreslår at denne automatonen også holder følge på alle medlemmers bursdager. En "bursdagsbot" 🎉
